### ISSUE TITLE
[BUG] "Accurate" Weapons no longer get an automatic accuracy die

### ISSUE THREAD

**Issue by The-E** [Eranziel/foundryvtt-lancer#188]
**Describe the bug**
A weapon that is tagged as "Accurate" no longer gets an accuracy die in the pre-roll dialogue

**To Reproduce**
1. Have a mech with an "accurate" weapon
2. Make an attack
3. See "accuracy" still at 0

**Expected behavior**
Accurate weapons get an automatic accuracy die

**Screenshots**
![image](https://user-images.githubusercontent.com/280879/117547623-d269cd00-b030-11eb-8c26-7dd9d5edb9bf.png)

**Platform (please complete the following information):**
 - OS: Linux (Heroku container, technically)
 - Browser MS Edge
 - Foundry version 0.7.9
 - Lancer system version 0.9.2

**Discord contact info**
The_E#1047

**Comment by ScyllPoesis** [comment]
Fixed with the new WIP acc/diff dialog (#192):
![image](https://user-images.githubusercontent.com/40338743/117576287-56fd2f80-b0b3-11eb-893b-25c2b73a1edb.png)

Appropriate tags found will be auto-checked, and the dialog will be built to support future synergies/active effects.

**Comment by Azmahel** [comment]
Just an Opinion, but not too much of a fan of the new UI, Seems a bit cluttered ( with more to come) and with so many ways to gain Accuracy/Difficulty it will never be exhaustive, and as such i'd actually prefer a simple field to enter the final value. Also this makes me second guess what is already factored in and what isn't. like: does seeking make the script ignore the cover fields? 

I would definitely like to have a field where I can see what the final Acc/Diff will be. that way i can at least see the effect the checkboxes have.

**Comment by VexxMyst** [comment]
I can somewhat agree on that, I think it's useful to have the checkmarks for easy reference, but they could be scaled down to around the size of the Loading checkbox, perhaps?
Definitely agree on having a "final acc/diff" value, the space to the right of Other Modifiers would be perfect.

**Comment by ScyllPoesis** [comment]
Yep! We're on the same page. In order:

- Styling is always up for discussion, by all means, rest assured WIP is WIP (I actually stole these boxes from another project of mine). As for the list itself, this is not supposed to be an exhaustive list; the checkboxes are just there for the most common fields we have in data that we can automate (the simple weapon tags and cover, which should constitute much of the Acc/Diff gains). Eventually we'll have synergies automated through Active Effects, but for now all your other effects are tallied just as before below, 
- Yes, the cover is disabled if seeking is checked.
- Yes, there is a final tally field. Due to Foundry's app rendering I couldn't finish the mock before mother's day shenanigans but the design has it. I since then decided it was clearer to break up the "other" field into two separate ones as before (Acc and Diff split). My design currently lands with two columns with the common effects, manual entry and a total at the bottom taking in the above two sections and summing it.

**Comment by ScyllPoesis** [comment]
This is closer to what I was thinking. Feel free to C&C.

![image](https://user-images.githubusercontent.com/40338743/117592106-542b2a80-b105-11eb-95e3-7961a551ed55.png)

**Comment by Azmahel** [comment]
that looks a ton better! thx.  Small thing: maybe add a (+) and (-) symbol to the Other Sources fields.

And maybe display Absolute Total which will be used for the roll (maybe instead of the subtotals, to not overload with Information)

**Comment by The-E** [comment]
I'd say that the subtotals are unecessary - the end total is what matters to players, and anyone who wants to do the math themselves probably doesn't need the additional help.

**Comment by ScyllPoesis** [comment]
> that looks a ton better! thx. Small thing: maybe add a (+) and (-) symbol to the Other Sources fields.

Can you elaborate where you'd like to see this? You mean like a + or - in front of the number in the input, or something else to divide the two sides clearly? Maybe the below will help?

> I'd say that the subtotals are unecessary - the end total is what matters to players,

Fair enough. Can do a bit of coloring in that case.  How about this?
![image](https://user-images.githubusercontent.com/40338743/117661713-b8350980-b16c-11eb-842a-ae5ab645a565.png)

**Comment by The-E** [comment]
That looks good to me.

**Comment by Azmahel** [comment]
Looks great.  I was talking about something in the vein of this (left OR right), but the divider alone helps a lot.
![acc](https://user-images.githubusercontent.com/18549435/117663526-095ef080-b1a1-11eb-88cf-1b477284fcba.png)

**Comment by ScyllPoesis** [comment]
Ah, that's what I thought. I personally think it's best not to repeat the icon too much but it's a matter of taste. I think the divider is a good subtle UI so I'll polish up the coloring swap and we'll go for this for the pilot. Cheers for the feedback.

**Comment by Azmahel** [comment]
that was just to show different options of doing it.  I i understtod ScyllPoesis correctly final version wont have extra icons. But the divider is enough to clear things up
