### ISSUE TITLE
[FEATURE] Damage Application

### ISSUE THREAD

**Issue by VexxMyst** [Eranziel/foundryvtt-lancer#189]
**Is your feature request related to a problem? Please describe.**
the Mess/Mars module has an feature where you can apply damage from a roll directly to a targeted character.

**Describe the solution you'd like**
If a roll is made against a targeted character, the GM can right-click on the character section and select 1/2x, 1x, or 2x damage. If full automation is desired, the GM could instead have a button next to the hit/miss marker that applies the damage, taking resistances and Exposed into account automatically.

**Describe alternatives you've considered**
See if Moerill would be interested in supporting Lancer with Mars. As the system already has hit detection and acc/diff integrated, the module's main functions seem redundant.

**Additional context**
A mockup showing both suggestions:
![lancerhitmock](https://user-images.githubusercontent.com/74265604/117553764-62077f80-b021-11eb-9f5b-989595280c33.PNG)

**Discord contact info**
VexxMyst#6669

**Comment by ScyllPoesis** [comment]
Manual damage application is in the cards, yes yes. We've discussed it internally and I have some basic designs for it, but still need to shop it out. Currently my idea is similar to MidiQOL's damage cards, which on hits will calculate what it thinks the damage should be for each target, listing out things like resistances and such, and allowing the GM to apply the suggested damage or half/double it if there are other factors it missed or aren't supported.

**Comment by msprijatelj** [comment]
To chime in with my 2 cents: I'd love it if automatic damage reduction/amplification could be applied for Resistance, Exposed, Armor, Miss-for-half-damage, etc, **_without_** the need for a GM to click to verify damage.  I'm just imagining scenarios where a Monarch or a Barbarossa hits a ton of enemies at once, and the number of clicks needed to verify the damage if I need to apply damage to each target on a case-by-case basis.  Ideally, I could roll damage once and have the system automatically take care of the rest.

**Comment by Eranziel** [comment]
While I agree that fully automatic would be great, the fact at the end of the day is that our data model can't account for all of Lancer's edge cases and special cases. *Especially* in cases like hitting many characters in one attack it is very likely that some of the damage would be applied incorrectly, making more work for the GM instead of less.

**Comment by msprijatelj** [comment]
I am sure that full Lancer damage automation, with all edge cases covered, would require a significant amount of developer effort.  However, I am not pushing for full damage automation, here.  I would be _beyond_ happy to see the automation of the 4-step Calculating Damage algorithm from pg. 67 of the Lancer Core Book.  

From the sounds of things, there are a reasonable number of characters (PCs or NPCs) that potentially break the damage calculation algorithm and could frustrate damage automation.  Given this concern, these are the best case/worst case scenarios I would anticipate given the presence and lack of damage automation:

### No Damage Automation

- **Best Case:** _All tokens follow the baseline algorithm:_ GM manually applies damage to each affected token, following the algorithm.
- **Worst Case:** _All tokens have a special rule that deviates from the baseline:_ GM manually applies the damage to each affected token, following the algorithm & deviating from it where directed by the tokens' special rules

### With Full Damage Automation, following the core book's Calculating Damage algorithm:

- **Best Case:** _All tokens follow the baseline algorithm:_ Damage automatically applied via algorithm, no GM input required
- **Worst Case:** _All tokens have a special rule that deviates from the baseline:_ Damage is applied automatically, GM manually corrects the damage to all tokens in accordance with the tokens' special rules

Most cases are going to fall between the best case and the worst case, of course, but if even a fraction of the tokens follow the standard damage calculation algorithm, the GM's job could get easier due to automation, as measured by number of manual intervention events.  With all that said, in order to understand the trade-offs between manually applying damage and correcting auto-applied damage, I have the following questions: 

- How much work is it for the GM to manually apply damage compared to manually correcting auto-applied damage? 
- How often is the worst case scenario a reality (aka how often are deviant rules encountered in the system)?

Answers to these questions that can clarify the current state of Lancer would be immensely helpful! I want to better understand the system so that I can contribute to it in a meaningful way.

**Comment by Eranziel** [comment]
Documenting recent discussions and the current plan. Damage application will end up as a 3 steps process for the user:
- Attacker starts an attack flow and uses the attack HUD to configure the attack rolls. Clicking "Roll" performs the roll and prints an attack card detailing the roll results, including crit/hit/miss if they had targets. The card will have at least 1 button for starting damage rolls.
- Attacker starts a damage flow and uses the (new) damage HUD to configure the damage rolls. This includes selecting/adding bonus damage to the entire roll, selecting/deselecting the targets and adding bonus damage for specific targets (looking at you, NucCav), a "1/2 damage" checkbox (for heavy gunner, Scylla, etc...). Clicking "Roll" performs the roll and prints a damage card detailing the roll results and appending a row for each target. Each row has buttons to apply 2x, 1x, or 1/2x damage.
  - If possible, make it a button with attached drop-down selector, with the default selection being 1x, or 2x if the target was exposed.
  - Ideally the damage application button for each row should be hidden or disabled once it has been used.
  - Multi-target bonus damage will be automatically halved separate from whichever multiple button is clicked.
- Targets each click the damage application button as appropriate, which prints a brief chat message stating the damage taken.
  - Ideally this should include an undo button which gets hidden once used.

Other surrounding discussion:
- The attack HUD doesn't need anything about damage/bonus damage added in. Any bonus damage sources which need to be declared prior to attacking can be done so verbally by the player, we don't need to add UI and enforce that resolution flow.
- The damage HUD obviously starts populated with the weapon's innate damage, and then allows adding bonus damage. Undecided if we will have semi-automated bonus damage selection - checkboxes for each source, e.g. OpCal, thermal charge, etc... - or if we will just leave it up to players to manually enter each bonus damage. The latter is certainly easier, since `lancer-data` doesn't provide complete data for the former.
- The damage HUD should be responsive to the user's canvas targeting. Therefore, clicking the damage button(s) in an attack card maybe should automatically re-target the appropriate tokens.
- We should be able to cleanly automate 2x damage for the exposed status. Clicking the 2x damage button should essentially force-enable the exposed damage calculation, it should not allow applying 4x damage.
- We plan to add statuses for type-specific resistances, which we can then automate for damage application. Almost every source of blanket resistance is conditional in some way; users can adjudicate that manually by using the "1/2x" button. (Which will only enable blanket resistance, it will not permit doubling up on resistance to a given type to result in 1/4 damage.)

**Comment by msprijatelj** [comment]
Some of my thoughts on the above:
- Agreed that user-manual bonus damage is best for an MVP release. Down the line, if  Lancer-data starts including Bonus Damage objects, we could maybe collect those then. 
- Hiding damage application button after use: I don’t think that’s completely necessary. Maybe someone undoes the damage because they forgot to apply resistance and then wants to apply damage again! The receiver of the damage will be accepting the damage anyway with a click. 
- I think we should think about the ½ damage less so in terms of resistance and moreso in terms of stuff like Heavy Gunner and HyperDense Armor. It’ll need to be handled, and it’s technically different from resistance (it occurs before Exposed and Armor), and it stacks with resistance itself.

**Comment by Eranziel** [comment]
I kind of buried the lede, but I was thinking of having a "1/2 damage" checkbox in the attacker's damage HUD, since non-resistance halving is all due to attacker's effects AFAIK. That and resistance definitely need to stack.

**Comment by lmilekic** [comment]
Hey friends, I hadn't looked at this in a little bit, but I made a SUPER **SUPER** rough PR with what I was thinking. I'm still both learning lancer + learning my way around the foundryvtt code. I was thinking as a super MVP just copying the style from pathfinder with 1/2, 1x and 2x damage (even if its not taking into account armor etc) might be nice. But in the past someone also put a lot of effort into calculating damage to be done to mechs so maybe we can reuse that code? I'm not familiar enough with lancer to confidently go through it and confirm if its handling all possible cases we care about. Here's what the pathfinder one looks like:
![image](https://github.com/user-attachments/assets/3c0d33c2-d6a5-40c3-8ee3-a0ff16069a99)

I put a pic of my super jank/ugly version in my PR.

**Comment by C-S-McFarland** [comment]
I did some testing today.

The enemy NPC mech (Pyro) has a flamethrower that has an effect on it that isn't covered in the automation. But applying exposed (to try and get double burn) doesn't apply to burn ... which is right. So, maybe we can add a drop-down to just apply double damage to help cover some of these random effects on weapons?

> This weapon deals double � to characters that already have any �.

**Comment by C-S-McFarland** [comment]
When I perform a basic tech attack, it gives me a roll damage option on the card. The roll damage seems to throw an error, but I'm not sure Invade should even have a damage roll?

**Comment by msprijatelj** [comment]
> When I perform a basic tech attack, it gives me a roll damage option on the card. The roll damage seems to throw an error, but I'm not sure Invade should even have a damage roll?

Invade innately inflicts 2 heat, which would be a valid use for the damage application algorithm. That said, basic tech attack can be used for things that aren’t Invade

**Comment by C-S-McFarland** [comment]
> Invade innately inflicts 2 heat, which would be a valid use for the damage application algorithm. That said, basic tech attack can be used for things that aren’t Invade, so applying a “blanket 2 Heat” may not be ideal.

Fair point. If that's possible, here is the error I'm getting.

![Screenshot 2024-09-26 at 3 49 02 PM](https://github.com/user-attachments/assets/e8087065-53c0-4f97-9dd2-cd446846750f)

**Comment by C-S-McFarland** [comment]
Ahh, I see, there are little crit/hit/miss markers in each target card inside the roll damage HUD.

**Comment by Eranziel** [comment]
@C-S-McFarland 
> When I perform a basic tech attack, it gives me a roll damage option on the card. The roll damage seems to throw an error, but I'm not sure Invade should even have a damage roll?

I'll add damage rolls for tech attacks/invades later, they need a bit more time in the oven. The Roll Damage button on tech attacks should be hidden properly now, if you pull the latest commits.

> When a roll damage for a multi target attack, the roll damage hud includes missed targets. Once I roll the damage, it only shows me a card for the mechs I hit, but it's a little confusing at this point why those mechs are there?

Yup, it's so that you can roll and apply reliable damage. I think I'll give target cards marked as "miss" a bit of a visual treatment so it's more obvious.

Thanks for the testing and feedback!

**Comment by Eranziel** [comment]
Complete as of 74e1cc0d6386554375c37a8ea77902fc05a52c55 !
