### ISSUE TITLE
[BUG] [0.9.3] Cannot add damage to npc weapons that don't already have damage

### ISSUE THREAD

**Issue by whitespine** [Eranziel/foundryvtt-lancer#218]
**Describe the bug**
See title. The T1/2/3 damage html stuff isn't even there

**To Reproduce**
Look at marker rifle

**Expected behavior**
Should show the damage listings, even if empty

**Screenshots**
![image](https://user-images.githubusercontent.com/16845226/121066567-094e1280-c798-11eb-911b-c1655c189ce6.png)

**Comment by Grygon** [comment]
I think this will only affect NPC Features that explicitly don't already have damage. Issue is that creating those results in a blank Damage array, rather than a Damage array with 3 arrays contained:
Marker Rifle:
![image](https://user-images.githubusercontent.com/647846/123040047-b63fa680-d3b8-11eb-9c54-f073c167f6e7.png)

Brand new NPC Feature:
![image](https://user-images.githubusercontent.com/647846/123040111-d53e3880-d3b8-11eb-94a5-5413a2f758b8.png)

Probably a tweak on compendium build? Either way, bumping to v1.1

**Comment by Eranziel** [comment]
Fixed in current dev, closing.
