### ISSUE TITLE
[BUG] Doing a new import on 0.8.7 doesn't link actors to items properly

### ISSUE THREAD

**Issue by Grygon** [Eranziel/foundryvtt-lancer#225]
**Describe the bug**
Primarily a bunch of console errors, but I _think_ we're losing some of the one-way linking that's used elsewhere too

**To Reproduce**
1. Launch server on 0.8.7
2. Import a pilot
3. Open Console

**Expected behavior**
Should work seamlessly, like on 0.8.6

**Screenshots**
![image](https://user-images.githubusercontent.com/647846/122275676-96d0e700-cea9-11eb-9d46-d1c9b40566d5.png)

**Platform (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Foundry version 0.8.7
 - Lancer system version 0.9.4

**Additional context**
This code is good to duplicate the issue: 78d3c986d75b174f7a6627af63d6b24e

**Comment by whitespine** [comment]
Are we sure this wasn't a result of my branch being merged?

**Comment by whitespine** [comment]
Just from reading the log it seems we might be adding items to an actor before it is actually added to the game.actors registry. If I had to extrapolate further, I imagine this is caused by a workflow change mentioned in the update notes, wherein actors that failed to initialize will still show up in the actors log. Probably, this means that the actors now . ready before they are accessible, which is pretty annoying! Might need to have some sort of short-term custom lookup dict

**Comment by Grygon** [comment]
Yup, it's working fine on 0.8.6

**Comment by VexxMyst** [comment]
I had an import bork after updating to 8.7, can confirm it's not from whitespine's branch since I don't have access to that.

**Comment by Grygon** [comment]
Completely unable to replicate this with 0.8.7/0.9.4 on both new or old worlds. Maybe just needed a server restart to set up the data model properly?

Going to leave this open for a bit to see if anyone else gets this still.

**Comment by Grygon** [comment]
Yeah closing
