### ISSUE TITLE
[BUG] pilot actors have no burn parameter.

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#271]
**Describe the bug**
Pilot actors have no burn parameter.

**To Reproduce**
1. Create a `pilot`
2. Examine the `data` of the pilot.
3. There is no field for burn, even though the field exists on the other actor types

**Expected behavior**
`pilot.data.data.burn` should hold the burn.

**Screenshots**
Pilot:
![image](https://user-images.githubusercontent.com/182554/128643450-36f49661-7f54-468b-9d69-f315d374bc5e.png)

Mech:
![image](https://user-images.githubusercontent.com/182554/128643503-df901181-d56c-4b25-9baf-79acb842d719.png)

**Platform (please complete the following information):**
 - OS: any
 - Browser: any
 - Foundry version: 0.8.8
 - Lancer system version: 0.9.5

**Discord contact info**
Bolts#9418

**Comment by whitespine** [comment]
This was fixed MM side at some point. template.json needs to be updated to reflect that pilots now track a `burn` and `overshield` (not `current_overshield`, as is currently tracked!)

I do not have time to handle this due to travel. @Eranziel if you could make these changes as part of the `current_` migration that would be wonderful.

**Comment by Eranziel** [comment]
Fix is done on `dev-1.0`.
