### ISSUE TITLE
[BUG] Mech Weapon Tags are duplicated

### ISSUE THREAD

**Issue by Alkyama** [Eranziel/foundryvtt-lancer#313]
**Describe the bug**
Mech Weapon tags are coming duplicated both on the sheets and on the Compendiums.

**To Reproduce**
1. Go to 'Compendium'
2. Click on 'Mech Weapon' to open the list
3. Open any weapon with a tag (e.g.: Howitzer)

**Expected behavior**
Seing only one instance of each tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/132264511-ac6d916b-394c-4134-85cf-ea25a03394d3.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Foundry version v0.8.9
 - Lancer system version 1.0.1

**Additional context**
Issue reported by other players on Pilot.net before, seems to be a known issue. This was tested on a world with only Token Action Hud activated.

**Discord contact info**
alkyama#2737

**Comment by mason-bially** [comment]
Possibly related to #249?

**Comment by mason-bially** [comment]
I believe it's related to `machine-mind`'s handling of profiles ( @whitespine ). Specifically [this line of code](https://github.com/whitespine/machine-mind/blob/active_overhaul2/src/classes/mech/MechWeapon.ts#L305) seems suspect, but I haven't found the actual erroneous code yet. Importantly however, profiled weapons appear to be working properly:

![image](https://user-images.githubusercontent.com/1072924/148667997-82dcf9a5-d80a-4593-9641-cf5839d115e3.png)

(from an external `.lcp` so it isn't a "bad copy of data" somewhere)

**Comment by mason-bially** [comment]
Should be fixed once whitespine/machine-mind#15 is merged and updated to.

**Comment by mason-bially** [comment]
Might as well record this here for people who still have this problem on the latest version with old worlds. First, as always, backup.

To fix this issue with an extant lancer system world you will have to ensure the compendiums are fixed first. To do this you will have to clear the compendiums (e.g. delete the contents of the "Mech Weapon" compendium) and then rebuild the lancer data and reimport any LCPs so that the compendium is then properly populated (make sure items from all your LCPs have been regenerated).

Then you will need to resync any characters/mechs. Due to the way the importer works, it may be required to delete these (or any offending items on them) and then reimport.
