### ISSUE TITLE
[BUG] Macros not generating from drag and dropping activation chips

### ISSUE THREAD

**Issue by erandisvol** [Eranziel/foundryvtt-lancer#357]
**Describe the bug**
Macros added to the hotbar by dragging abilities from the mech sheet do not create a functioning macro. The icon and label are created correctly, but the script is blank. This includes actions added by Pilot Talents such as Hacker rank 2

**To Reproduce**
1. Create a mech sheet.
2. Add a system such as H0R_OS System Upgrade or Swarm Body
3. Drag the appropriate action button on the system to the macro bar, such as "Quick" "Quick Tech" or "Invade"

**Expected behavior**
A macro would be created for executing the action similar to dragging a weapon attack to the macro bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/74384720/137019343-3d300423-34e5-4646-8cd3-12744029e981.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Foundry version 0.8.9
 - Lancer system version 1.0.3

**Additional context**

**Discord contact info**
Laughing Octopus#0860

**Comment by Eranziel** [comment]
Related to #374.

**Comment by mason-bially** [comment]
Better name would be "Macros not generating from drag and dropping activation chips".

**Comment by mason-bially** [comment]
That commit should fix it.

Looking into the NPC ones now.

**Comment by msprijatelj** [comment]
Macros appear to be correctly generating for mech weapons; they follow back to the actor/token and register when certain effects are upon them (e.g. the Impaired condition). Woohoo!

For NPC weapons/systems, macros are generating, but seem tied to the original actor; attempting to 2 weapon attack macros with the same weapon from 2 different NPC tokens for the same NPC actor actually only generates 1 macro.  Effects on a specific token (like the Impaired condition) are only accounted for when the macro is activated while the token is selected.

In fairness, this NPC issue probably isn't too big of a deal since creating a macro bar for all individual NPC tokens would be tedious for the user.  Chances are, they'd probably use something like Token Action Hud or just Select + Use macro when it really matters.  To be honest, making the NPC macros easier to access on the NPC sheet itself would probably be a more worthwhile feature than judiciously instantiating macros for every NPC token created.

**Comment by mason-bially** [comment]
I am actually working on improving drag and drop macro experience still, I didn't manage to get it into the latest version, see issue #374 for some of my thoughts.

**Comment by Eranziel** [comment]
Going to mark this one as fixed with Mason's PR. There's still a few rough edges, but I think they're documented in #374 and related issues.
