### ISSUE TITLE
[FEATURE] Combat Assistance Improvements

### ISSUE THREAD

**Issue by ScyllPoesis** [Eranziel/foundryvtt-lancer#426]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when the system I built a year ago (action tracker) wasn't finished when my group collapsed and I became sad. Additionally there are other minor-cost issues that could improve the general feel and speed of running combats.

**Describe the solution you'd like**
Update the action tracker to handle new combat turn data, improve usability and interaction across the system (reset actions to default, view from mech sheet), and explore additional improvements to the system such as any fixes to macros and features like damage cards. If these features are not found to be cheap they will be spun off to a separate issue.

**Describe alternatives you've considered**
I've definitely considered not doing this. 

**Additional context**

**Discord contact info**
Scyll#7878

**Comment by mason-bially** [comment]
I'm currently working on a UI overhaul of the current cards to tighten them up, specifically so that I could separate Attack Rolls and Damage Rolls and then introduce things like "damage applied" and "status effect added/removed" cards (including a "request status effect add/remove" gm-whisper card that can mutate to the past tense to fix #397 ). It was my goal that with the UI refactor I could fit all of this in roughly the same amount of space as a single current attack card.

Another longer term goal of this was to create cards for start of turn/end of turn to track turns. This would then allow us to use the cards to track actions as well (I was planning to track both usages and current remaining in a line on the header, but that might be over doing it).

**Comment by ScyllPoesis** [comment]
Excellent to hear. I'll leave the UX work to you then, and what I can do is just make a simple card tied to the combat turn automation that you can then use as a base when you finalize the refactor.

The above commit fixes the combat tracker and brings online the turn based automation which already logs to console. I'll go ahead and build up the simple cards as described above and add some settings to moderate all this, and call it good for testing.

**Comment by mason-bially** [comment]
That sounds excellent!

To be clear there is a macro rafactor in #374 I wanted to do to make a macro set for "triggering action X" that's separate from "displaying X". So that using a system prints the system (perhaps collpased by default) to track the usage, where as displaying the system will just display it and not the "used an action" symbol (perhaps uncollapsed by default). Both on the same card.

Not sure what you are doing with the macros as part of this action system refactor.

**Comment by mason-bially** [comment]
I also, long term, would like a way to trigger user macros for actions, namely to off load the maintenance burden (and licensing issues). This will likely include parts of core actions. I'm not sure if you were planning on adding core actions (like barrage yet).

Anyway I'm currently messing around with splitting up the attack macros and tieing them into that macro refactor a little better at the moment. I can try to hurry that up to get out of your way if you *do* plan on improving the action macros.

**Comment by ScyllPoesis** [comment]
> So that using a system prints the system (perhaps collpased by default) to track the usage...
This is an important step if we want to automate action usage, yes yes. Similar to how 5e lets you "cast" spells to chat without consuming a slot to skip the resource check. Good plan to me. 

And please take your time. Building pop-ups for the discrete actions is definitely a cool idea but outside my immediate scope; this is pertaining mainly to tracking the actions as resources. I'll leave the action macros themselves as is/to you for now as they're much closer tied to the automation and UX you're working with. The scope of what I'm tackling now is keyed to the tracking of the underlying action economy which is available to the system as a whole, and making it more user friendly to deal with (manually, for now).

**Comment by ScyllPoesis** [comment]
Alright, as usual just sort of belted this out all at once. To review:

- Action tracking via the hotbar has been fixed and reconnected back to combat turn automation. It has also been re-enabled on mech sheets if the actor is found to be present in the current combat.
- Action tracking itself can now be accessed regardless of the state of the action manager (the hud app), and is now a separate module found at `module/action/actionTracker.ts`. Given an `actor` this allows any macros to retrieve and modify action data, supporting future automations.
- Action tracking settings have been established similar to the existing automation settings. Currently these are showing the hotbar, allowing players to modify their own actions, and printing turn start/end status updates (mainly as a proof of concept for the above referenced UX updates).

**Comment by ScyllPoesis** [comment]
Added small fix to attack rolls, to stop it from updating the heat if there was no change, as any updates currently re-render and reset the entire sheet (which is annoying).

**Comment by ScyllPoesis** [comment]
Fixed bug where turn/round combat automation was triggering on all logged in players, now restricted only to the GM. Additionally fixed a hook error with the new central action tracking.
