### ISSUE TITLE
[BUG] Strictly lowercase email/username

### ISSUE THREAD

**Issue by tachester** [Eranziel/foundryvtt-lancer#527]
**Describe the bug**
To sign into compcon through foundry the email MUST be lowercase, this is counterintuitive to pretty much all other websites I've ever come across. The email should be case insensitive; this could be solved via a manual conversion to lowercase in the code base, if necessary.

**Discord contact info**
Archiver #1883

**Comment by msprijatelj** [comment]
Ironically, CompCon used to accept case sensitive emails, so it needs to support case sensitivity in the default case in order to let those accounts still work. It may be possible to add a fallback case of lowercase email address though? That’s what compcon currently uses to support legacy accounts.

**Comment by tachester** [comment]
I updated my pull request with this fix. I literally just added the second case-insensitive login in the catch block of the first case-sensitive login. It looks a bit messy, but it should work.

https://github.com/Eranziel/foundryvtt-lancer/pull/528

**Comment by msprijatelj** [comment]
Nice! And yeah I think it was mostly just an oversight at the time, but it certainly has caused a more than a few headaches on the CompCon end.
