### ISSUE TITLE
[BUG] Structure checks do not roll for Cascade

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#594]
**Describe the bug**
When a mech with an AI system is structured, it is supposed to also roll to see if the NHP begins cascade. The system does not perform this roll.

**To Reproduce**
1. Cause a structure check on a mech with an AI system installed.
2. The cascade d20 is not rolled.

**Expected behavior**
Structure checks should automatically roll for cascade.

**Comment by dodgepong** [comment]
Worth noting that Iconoclast 1's Unstable NHP is not marked with the AI in the LCP as a hack in order to let people add two AIs to their mech in CompCon.

Meanwhile, the Technophile 3 Enlightenment-Class NHP does not have the AI tag either, though _technically_ it is able to cascade, if the PC wants them to.

**Comment by Eranziel** [comment]
Structure cards now include a "CASCADE" button if the mech has any AI systems, so considering this finished.
