### ISSUE TITLE
[FEATURE] Add integration for Combat Carousel 

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#605]
**Is your feature request related to a problem? Please describe.**
Combat Carousel will no longer receive support for Foundry v11+. The module still functions in v11, but may not in future versions of Foundry.

**Describe the solution you'd like**
Add integration code in our system for [Carousel Combat Tracker](https://github.com/theripper93/combat-tracker-dock) as well, to future-proof and maintain carousel support for users who wish to switch over to it instead of Combat Carousel.

**Comment by BoltsJ** [comment]
1. I don't know that the code will be refactorable from one module to the other.
2. The older module is still fully working on v11, so we shouldn't remove the integration for now.

**Comment by Eranziel** [comment]
You're right, Combat Carousel still works. I assumed that some parts of it would be non-functional since it is not being updated to support v11.

In light of that, I'll reword the issue description. We should _add_ support for Carousel Combat Tracker for future proofing or whoever wants to migrate to it. Much less urgent, though, since Combat Carousel is still functional.

**Comment by BoltsJ** [comment]
Yeah. If past experience is anything to go by, the new module will have to be patched to not outright break due to lancer initiative. I submitted patches to combat carousel as part of building the integration. 

Uh, looking into it, the new one doesn't have a public license and an obfuscated git history, so I don't think it's open to contributions, and since the old one was GPL3, that's a pretty clear indication that it's not a fork so I'm willing to put my chips down on it needing a complete rewrite.
