### ISSUE TITLE
[BUG] Machine Mind store fails to load due to modified Compendium Items

### ISSUE THREAD

**Issue by SgtBriar** [Eranziel/foundryvtt-lancer#78]
**Describe the bug**
All the character sheets on the current world revert to the default Foundry character sheet and can't be changed back to the Lancer one.

**To Reproduce**
I don't know how to reproduce this.

**Expected behavior**
To have the Lancer character sheets exist.

**Screenshots**

**Desktop:**
 - OS: Windows 10 Home
 - Browser: Mozilla Firefox
 - Version: 10.0 Build 18363

**Additional context**
Issue resolved by deleting existing Compendiums, then reloading them.
![FoundryVTT_2020-10-03_09-04-40](https://user-images.githubusercontent.com/72285347/94978560-3a1edd80-0561-11eb-8770-6cfacbdace94.png)

**Comment by Eranziel** [comment]
This seems to be caused by editing a weapon inside one of the auto-generated Compendiums, causing the tags to change from an array to an object. When the `machine-mind` store attempts to initialize it fails because the tags are not an array.

Two root causes:
1. Tags getting changed to an object. Need to fix the sheet data to transform back to array before updating the item.
2. Compendiums are not getting locked when the LCM is done with them.
